import { ArrowRight, Sparkles, Gauge, GitBranch } from "lucide-react";
import { Button } from "../components/ui/button";
import { AgentCard } from "../components/AgentCard";
import { featuredAgents } from "../lib/mock-data";
import type { NavKey } from "../components/Layout";

export function Landing({ onNav }: { onNav: (k: NavKey) => void }) {
  return (
    <div>
      {/* AgentHub · Generated by Prep-01 */}
      {/* [Prep-02] 修复 #1: 收紧 Hero 垂直留白与字号，对齐 linear.app 信息密度 */}
      <section className="mx-auto max-w-7xl px-6 pt-12 pb-10 md:pt-16 md:pb-12">
        <div className="mx-auto max-w-3xl text-center">
          <div className="inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-3 py-1 text-[12px] text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5 text-primary" />
            v0.7 已上线 · 支持 MCP 工具调用
          </div>
          <h1 className="mt-5" style={{ fontSize: 30, lineHeight: 1.25 }}>
            把 AI Agent 像 npm 包一样安装、组合、上线
          </h1>
          <p className="mt-3 text-[14px] text-muted-foreground">
            AgentHub 是 AI Agent 的商店与 Playground 平台。浏览精选 Agent，在线试用，三行代码接入到你的产品。
          </p>
          <div className="mt-6 flex items-center justify-center gap-3">
            <Button onClick={() => onNav("gallery")}>
              浏览 Agent 商店<ArrowRight className="ml-1 h-4 w-4" />
            </Button>
            <Button variant="outline" onClick={() => onNav("detail")}>打开 Playground</Button>
          </div>
          <div className="mt-3 text-[12px] text-muted-foreground">在线演示，无需注册</div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6">
        <div className="mb-6 flex items-end justify-between">
          <div>
            <h2 style={{ fontSize: 20 }}>精选 Agent</h2>
            <p className="text-[13px] text-muted-foreground">编辑团队每周更新的高质量 Agent</p>
          </div>
          <Button variant="ghost" size="sm" onClick={() => onNav("gallery")}>查看全部 →</Button>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {featuredAgents.map((a) => (
            <AgentCard key={a.id} agent={a} onClick={() => onNav("detail")} />
          ))}
        </div>
      </section>

      {/* [Prep-02] 修复 #1: section 间距从 96/128 改为 64/80 */}
      <section className="mx-auto max-w-7xl px-6 py-16">
        <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
          {[
            { icon: Sparkles, title: "生成式 UI 流式渲染", desc: "Agent 不只输出文字，组件、表格、图表也能实时拼装出来。" },
            { icon: Gauge, title: "Token 用量事前预估", desc: "运行前准确预估成本，按团队、按项目分配预算。" },
            { icon: GitBranch, title: "Trace 执行瀑布图", desc: "每一次工具调用、每一段思考都可追溯，快速定位问题。" },
          ].map((v) => (
            <div key={v.title} className="rounded-lg border border-border bg-card p-6 shadow-sm">
              <div className="flex h-9 w-9 items-center justify-center rounded-md bg-primary/15 text-primary">
                <v.icon className="h-5 w-5" />
              </div>
              <h3 className="mt-4" style={{ fontSize: 16 }}>{v.title}</h3>
              <p className="mt-2 text-[13px] text-muted-foreground">{v.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="border-y border-border bg-card/40">
        <div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-6 py-12 md:grid-cols-4">
          {[
            ["500+", "个 Agent"],
            ["1 万+", "开发者"],
            ["5000 万+", "次运行"],
            ["99.9%", "可用性"],
          ].map(([n, l]) => (
            <div key={l}>
              <div style={{ fontSize: 30 }}>{n}</div>
              <div className="mt-1 text-[13px] text-muted-foreground">{l}</div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
